### ISSUE TITLE
Converting from Rpres 

### ISSUE THREAD

**Issue by b1azk0** [RealOrangeOne/hugo-theme-revealjs#1]
Hi,
I just found your theme demo on hugo templates and tried to give it a go with my RMarkdown presentations.
Is there a straightforward way to convert `rpres` files into this template?
A typical presentation I used to build was structured according to RStudio defaults:

```
Title
========================================================
author: 
date: 
autosize: true

First Slide
========================================================

For more details on authoring R presentations please visit <https://support.rstudio.com/hc/en-us/articles/200486468>.

- Bullet 1
- Bullet 2
- Bullet 3

Slide With Code
========================================================
{r}
summary(cars)
``` 

Your template, from what I managed to understand requires separate `.md` files for each slide - is this the only way to go?

**Comment by RealOrangeOne** [comment]
Each slide has to be a single file, yes. When compared to a standard Hugo site, each page is a single slide, and a section is a vertical group of slides. The chances of Hugo supporting multiple pages in 1 file is very remote. And I know for a fact now that `rpres` files are unsupported by Hugo. 

For support for `rpres` files to become supported, changes will need to be made to Hugo rather than this project:
- Support more than 1 page per file
- Support for `rpres` as an external format

Due to the fact that all required changes must be done upstream, i'm closing this issue.
