### ISSUE TITLE
Question: How to add pictures to slides in Hugo

### ISSUE THREAD

**Issue by GITchristoph** [RealOrangeOne/hugo-theme-revealjs#4]
Hi

(First of all sorry that I left this other issue open so long. I actually forgot about it. Sorry again).

My question is it is possible to add pictures to the presentations?
I did not find a way how to do that.

I tried generally to add it to the md file (same as on other Hugo sites:

```
---
title: Reaveal website
image: "profile.png"
weight: 100
---
  #### Subtitle
```

I tried to place the related picture directly in the same folder as the .md file and in static.
But it did not show on the website.

I tried to add fragments but wasn't successful
```
{{% background-image="profile.png" %}}
```

I hope it's a simple one to answer.

Thanks a lot in advance for your help,

Chris

**Comment by RealOrangeOne** [comment]
If you want to set the background, you'll need to set the `background` frontmatter.

If you want to embed images into content, you'll need to use the regular markdown syntax for embedding images.

Unless specified otherwise, images need to be absolute paths. Currently there's no way to specify a [page resource](https://gohugo.io/content-management/image-processing/#the-image-page-resource) for those images, but i'd definitely welcome a PR!

**Comment by GITchristoph** [comment]
Hi @RealOrangeOne 

I do not understand the part about setting the background frontmatter but the Markdown syntax works. Thanks a lot!

As an example (maybe also for other beginners), the following Markdown Syntax will add a picture in the same folder as the .md file:

```
![alt text](profile.png)
```
It creates a white border around the image though, which I have not found out yet how to change this.

@RealOrangeOne , would it be ok for you to give me a hint in what file I should adjust this? That would be very much appreciated :-)

Chris
